### ISSUE TITLE
Support Gnome 44

### ISSUE THREAD

**Issue by benotn** [lucaswerkmeister/activate-window-by-title#2]
Hi, thank you very much for this extension!

Gnome 44 is now out and your extension officially supports only versions 42 and 43. I made a quick test by adding 44 to the "shell-version" array in metadata.json and so far everything works as usual.

Could you officially upgrade support of this extension to version 44?

**Comment by lucaswerkmeister** [comment]
Arch has been a bit slow with rolling out GNOME 44 (no idea why), so I haven’t been able to test it myself yet, but I’ll see what I can do.
