### ISSUE TITLE
A very good tool to integrate with ydotool

### ISSUE THREAD

**Issue by vhbui02** [lucaswerkmeister/activate-window-by-title#6]
It really helps in my automation workflow that's currently using `ydotool` on my Ubuntu Wayland.
If you haven't known yet, ydotool can't send keystroke or type or click, ... on any windows that's not currently focusing, as mention in this github issue: https://github.com/ReimuNotMoe/ydotool/issues/140
By integrating ydotool with this tool, now you can focus first using activate-window-by-title, then apply ydotool.
Thank you Lucas for writing such an amazing tool.

**Comment by lucaswerkmeister** [comment]
Nice to hear, I’m glad it’s useful to you :)
